# github.com/go-task/task

version: '3'

vars:
  BINARY_NAME: stream-queue
  VERSION: v0.0.1

tasks:
  docker:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      -  go mod tidy
      -  go mod vendor
      -  docker build --build-arg VERSION={{.VERSION}} . -t kubemq/{{.BINARY_NAME}}:{{.VERSION}}
      -  docker tag kubemq/{{.BINARY_NAME}}:{{.VERSION}} kubemq/{{.BINARY_NAME}}:latest
  push:
    cmds:
      - docker push kubemq/{{.BINARY_NAME}}:{{.VERSION}}
      - docker push kubemq/{{.BINARY_NAME}}:latest

  release:
    cmds:
      - task: docker
      - task: push

